// In this file you can specify the trial data for your experiment


const key_press_trials = _.shuffle([
    {
        question: "Are the two figures the same or different?",
        picture: 'images/1_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 01,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/1_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 01,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/1_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 01,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/1_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 01,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/2_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 02,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/2_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 02,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/2_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 02,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/2_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 02,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/3_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 03,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/3_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 03,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/3_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 03,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/3_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 03,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/4_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 04,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/4_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 04,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/4_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 04,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/4_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 04,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/5_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 05,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/5_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 05,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/5_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 05,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/5_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 05,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/6_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 06,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/6_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 06,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/6_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 06,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/6_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 06,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/7_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 07,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/7_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 07,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/7_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 07,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/7_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 07,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/8_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 08,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/8_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 08,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/8_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 08,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/8_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 08,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/9_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 09,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/9_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 09,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/9_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 09,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/9_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 09,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/10_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 10,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/10_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 10,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/10_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 10,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/10_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 10,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/11_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 11,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/11_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 11,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/11_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 11,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/11_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 11,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/12_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 12,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/12_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 12,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/12_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 12,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/12_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 12,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/13_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 13,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/13_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 13,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/13_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 13,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/13_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 13,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/14_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 14,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/14_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 14,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/14_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 14,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/14_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 14,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/15_50_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 15,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/15_50_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 15,
        degree_of_rotation: 50
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/15_150_different.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'different',
        number_of_picture: 15,
        degree_of_rotation: 150
    },
    {
        question: "Are the two figures the same or different?",
        picture: 'images/15_150_same.jpg',
        key1: 's',
        key2: 'd',
        s: 'same',
        d: 'different',
        expected: 'same',
        number_of_picture: 15,
        degree_of_rotation: 150
    },
]);

const practice_trials = _.dropRight(key_press_trials, 48);

const main_trials = _.drop(key_press_trials, 12);